name: tailor_billing
description: Tailor Billing App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  uuid: ^4.3.3
  provider: ^6.1.1
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  file_picker: ^8.0.0
  flutter_native_contact_picker: ^0.0.7
  http: ^1.2.2
  url_launcher: ^6.2.5
  pdf: ^3.11.3
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/app_icon.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
